"""
Django settings for dds_manager project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aiwdmec1y)te(1pz)0eu2tnpm#$p=l3qd6j74!ubzmte(*vn83'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Разрешенные хосты для приложения
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',        # Админка Django
    'django.contrib.auth',         # Система аутентификации
    'django.contrib.contenttypes', # Система типов контента
    'django.contrib.sessions',    # Управление сессиями
    'django.contrib.messages',    # Система сообщений
    'django.contrib.staticfiles', # Обработка статических файлов
    'core',                       # Наше основное приложение для ДДС
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Безопасность
    'core.middleware.SQLInjectionProtectionMiddleware',        # Защита от SQL-инъекций
    'core.middleware.SecurityHeadersMiddleware',              # Заголовки безопасности
    'django.contrib.sessions.middleware.SessionMiddleware',    # Сессии
    'django.middleware.common.CommonMiddleware',              # Общие функции
    'django.middleware.csrf.CsrfViewMiddleware',              # CSRF защита
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Аутентификация
    'django.contrib.messages.middleware.MessageMiddleware',    # Сообщения
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Защита от clickjacking
]

ROOT_URLCONF = 'dds_manager.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Дополнительные директории шаблонов
        'APP_DIRS': True,  # Искать шаблоны в папках приложений
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',     # Объект request
                'django.contrib.auth.context_processors.auth',    # Пользователь
                'django.contrib.messages.context_processors.messages', # Сообщения
            ],
        },
    },
]

WSGI_APPLICATION = 'dds_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite для простоты разработки
        'NAME': BASE_DIR / 'db.sqlite3',         # Путь к файлу базы данных
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'  # Русский язык по умолчанию

TIME_ZONE = 'Europe/Moscow'  # Московское время

USE_I18N = True  # Включить интернационализацию

USE_TZ = True  # Использовать часовые пояса


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # URL для статических файлов
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Дополнительные директории со статическими файлами
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки безопасности
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CSRF настройки
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# Session настройки
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Логирование для мониторинга безопасности
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'core.middleware': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'core.views': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Настройки безопасности
# Отключение middleware защиты для разработки
DISABLE_SECURITY_MIDDLEWARE = False  # Установите True для отключения middleware
